//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaBD
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RESENIAS
    {
        public int id { get; set; }

        [Required(ErrorMessage = "El campo Resenia es obligatorio.")]
        [StringLength(1000, ErrorMessage = "El campo Resenia no debe tener más de 1000 caracteres.")]
        public string resenia { get; set; }
        [Required(ErrorMessage = "El campo Comentario es obligatorio.")]
        [StringLength(500, ErrorMessage = "El campo comentario no debe tener más de 500 caracteres.")]
        public string comentario { get; set; }
        [Required(ErrorMessage = "El campo Calificacion es obligatorio.")]
        public int calificacion { get; set; }
        [Required(ErrorMessage = "La referencia de libro es obligatorio.")]
        public int idLibro { get; set; }
        [Required(ErrorMessage = "El usuario es obligatorio es obligatorio.")]
        public int idUsuario { get; set; }
    
        public virtual LIBROS LIBROS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
