//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaBD
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIOS()
        {
            this.RESENIAS = new HashSet<RESENIAS>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "El campo Documento es obligatorio.")]
        public string documento { get; set; }

        [Required(ErrorMessage = "El campo Nombre Completo es obligatorio.")]
        public string nombreCompleto { get; set; }

        [Required(ErrorMessage = "El campo Email es obligatorio.")]
        [EmailAddress(ErrorMessage = "El campo Email no tiene un formato de correo electrónico válido.")]
        public string email { get; set; }

        [Required(ErrorMessage = "El campo Clave es obligatorio.")]
        [DataType(DataType.Password)]
        public string clave { get; set; }

        [Required(ErrorMessage = "El campo Confirmar Clave es obligatorio.")]
        [DataType(DataType.Password)]
        public string confirmarClave { get; set; }  
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESENIAS> RESENIAS { get; set; }
    }
}
